### ISSUE TITLE
Taiga is not an online git service

### ISSUE THREAD

**Issue by greenled** [emptymalei/awesome-research#18]
I think Taiga is on the wrong place, as it's not an "online git service". On the website you can read "Taiga is a project management platform for agile developers & designers and project managers who want a beautiful tool that makes work truly enjoyable". Perhaps it integrates with online git services like Github, Gitlab and Gogs.

**Comment by emptymalei** [comment]
@greenled Great catch. It was a git service but I guess they transformed into this project management tool. Thank you.

**Comment by greenled** [comment]
Didn't knew it. I found it already being an agile project management tool. Thank you for the hard work curating the list!

**Comment by emptymalei** [comment]
@greenled If you don't mind I am gonna close this issue since we have solved the problem.

**Comment by greenled** [comment]
Sure, no problem. I close it by myself.
