### ISSUE TITLE
Dead link - "Cloud Based Markdown Editors"

### ISSUE THREAD

**Issue by jhwohlgemuth** [emptymalei/awesome-research#4]
**Dead LInk**: `Writing` > [Cloud Based Markdown Editors](https://github.com/emptymalei/awesome-research/blob/master/Cloud-Services.html)

I really appreaciate the effort you put into this awesome list...so, I thought I would help make it more awesome. :bowtie:

**Comment by emptymalei** [comment]
Thanks. It is now fixed.
