### ISSUE TITLE
Add obsidian to somewhere

### ISSUE THREAD

**Issue by suanzy** [emptymalei/awesome-research#53]
I am very sure this will be helpful but I am too tired now to think which category it belongs (and I could have forget after I close this tab), just in case I am too occupied to come back:
- the Obsidian official page: https://obsidian.md/
- the Obsidian awesome list: https://github.com/kmaasrud/awesome-obsidian

**Comment by emptymalei** [comment]
Hi @suanzy thanks for the comment.
This repo is mostly stale and we have moved most of the stuff to a website. Obsidian is already included there:
https://tools.kausalflow.com/tools/obsidian/

The second repo you mentioned seems very useful. I'll add it to the website too.

**Comment by userrand** [comment]
Maybe it should be mentioned in the readme that the link has more tools
